export const queryKeys = {
  me: ["me"] as const,
  users: (q?: string) => ["users", q ?? ""] as const,
  projects: () => ["projects"] as const,
  allProjects: () => ["projects", "all"] as const,
  project: (projectId: string) => ["projects", projectId] as const,
  stages: (projectId: string) => ["projects", projectId, "stages"] as const,
  labels: (projectId: string) => ["projects", projectId, "labels"] as const,
  tasks: (projectId: string, filters?: Record<string, string | undefined>) =>
    ["projects", projectId, "tasks", filters ?? {}] as const,
  task: (taskId: string) => ["tasks", taskId] as const,
  subtasks: (taskId: string) => ["tasks", taskId, "subtasks"] as const,
  timeEntries: (taskId: string) => ["tasks", taskId, "time-entries"] as const,
  comments: (taskId: string) => ["tasks", taskId, "comments"] as const,
  myTasks: () => ["my-tasks"] as const,
  mentions: () => ["mentions"] as const,
  notifications: () => ["notifications"] as const,
  notificationsCount: () => ["notifications", "count"] as const,
  roles: () => ["roles"] as const,
  timeLogToday: () => ["timeclock", "today"] as const,
  leavesAll: () => ["leaves", "all"] as const,
  leavesMine: () => ["leaves", "mine"] as const,
  channels: () => ["channels"] as const,
  messages: (channelId: string) => ["channels", channelId, "messages"] as const,
  platformOrganizations: () => ["platform", "organizations"] as const,
  platformDevelopers: () => ["platform", "developers"] as const,
  platformProjects: () => ["platform", "projects"] as const,
  idCard: (userId: string) => ["id-card", userId] as const,
};
